# Generated by Django 4.2.22 on 2025-06-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("agent_name", "key")},
            },
        ),
    ]
