# Generated by Django 5.0.6 on 2024-07-25 12:00

from django.db import migrations

def add_kiarash_bashokian_info(apps, schema_editor):
    AgentMemory = apps.get_model('core_services', 'AgentMemory')
    
    # Comprehensive information about Kiarash Bashokian
    kiarash_info = """
Kiarash Bashokian is a skilled Backend Developer based in Toronto, Canada, with a strong background in IT infrastructure. He specializes in creating scalable, high-performance web solutions using both Monolithic and Hybrid architectures.

**Key Skills & Technologies:**

*   **Programming Languages:** Python, Java, JavaScript, C, C++, Bash, Shell Script
*   **Backend Frameworks:** Django, Django REST Framework (DRF), FastAPI, Flask, Celery
*   **Databases:** PostgreSQL, MySQL, SQLite, MongoDB, Redis, Oracle, SQL Server
*   **Frontend:** React, HTML/CSS, Tailwind CSS
*   **DevOps & Cloud:** Docker, NGINX, Apache, Git, GitHub Actions, Linux Server Administration (Arch, Ubuntu, Debian)
*   **APIs & Testing:** REST APIs, Postman, pytest, unittest
*   **Networking:** Network Infrastructure Management, CCNA, NETWORK+

**Professional Experience:**

*   **Web Developer at Gh Light (Tehran, Iran | 03/2024 - 05/2024):** Developed a website, handling backend, frontend, SEO, and database components. Gained experience in system optimization and related development tasks.
*   **IT Expert at Arya heavy machinery (Tehran, Iran | 11/2023 - 02/2024):** Managed HP servers, administered vCenter, configured firewalls and network equipment, and provided support for network-based software like SAP.
*   **Trainee at Qt Framework (Tehran, Iran | 09/2022 - 12/2022):** Enhanced skills in C++ and C, focusing on object-oriented programming (OOP) and memory management while learning to design and work with the Qt framework.

**Education:**

*   **Bachelor of Computer Science: Software** from York University, Toronto, Ontario, Canada (Expected Graduation: 02/2025).

**Online Profiles:**

*   **Website:** [https://kiarashbashokian.com/](https://kiarashbashokian.com/)
*   **GitHub:** [https://github.com/Ghosts6](https://github.com/Ghosts6)
*   **LinkedIn:** [https://www.linkedin.com/in/kiarashbashokian/](https://www.linkedin.com/in/kiarashbashokian/)
"""

    # Create a list of questions and the corresponding answer
    qa_pairs = {
        "who is kiarash bashokian": kiarash_info,
        "tell me about kiarash bashokian": kiarash_info,
        "what are kiarash bashokian's skills": "Kiarash Bashokian has a wide range of skills, including: Python, Django, FastAPI, Flask, JavaScript, React, C++, Java, and more. He is also experienced in database management with PostgreSQL, MySQL, MongoDB, and Redis, as well as DevOps tools like Docker and Git.",
        "what is kiarash bashokian's experience": "Kiarash Bashokian has worked as a Web Developer at Gh Light, an IT Expert at Arya heavy machinery, and a trainee at Qt framework. He has experience in backend development, system optimization, network administration, and software development with C++ and Qt.",
        "where did kiarash bashokian study": "Kiarash Bashokian is currently pursuing a Bachelor of Computer Science in Software at York University in Toronto, Canada, with an expected graduation date of February 2025.",
    }

    for question, answer in qa_pairs.items():
        AgentMemory.objects.update_or_create(
            agent_name='qa',
            key=question,
            defaults={'value': answer}
        )

def remove_kiarash_bashokian_info(apps, schema_editor):
    AgentMemory = apps.get_model('core_services', 'AgentMemory')
    questions = [
        "who is kiarash bashokian?",
        "what are kiarash bashokian's skills?",
        "what is kiarash bashokian's experience?",
        "where did kiarash bashokian study?",
    ]
    AgentMemory.objects.filter(agent_name='qa', key__in=questions).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RunPython(add_kiarash_bashokian_info, remove_kiarash_bashokian_info),
    ]