[pytest]
DJANGO_SETTINGS_MODULE = ai_agent.backend_core.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = . ..
asyncio_mode = strict

filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning

env = 
    TEST_MODE=True