name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10.12, 3.11]

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: 📄 Create .env file
        run: |
          cat <<EOF > ai_agent/.env
          DJANGO_SECRET_KEY=test-secret
          DJANGO_DEBUG=True
          DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
          DATABASE_NAME=test_db
          DATABASE_USER=test_user
          DATABASE_PASSWORD=test_pass
          DATABASE_HOST=localhost
          DATABASE_PORT=5432
          OPENAI_API_KEY=dummy-key
          CELERY_BROKER_URL=redis://localhost:6379/0
          TEST_MODE=True
          # Optional future use:
          # DNA_API_URL=
          # DNA_USERNAME=
          # DNA_PASSWORD=
          # LOG_LEVEL=
          EOF

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ⚙️ Prepare Django project
        working-directory: ai_agent
        run: |
          python manage.py flush --no-input
          python manage.py migrate

      - name: 🧪 Run Pytest
        working-directory: ai_agent
        env:
          DJANGO_SETTINGS_MODULE: ai_agent.settings
          PYTHONWARNINGS: ignore
        run: |
          python manage.py collectstatic --noinput
          python manage.py flush --no-input
          python manage.py migrate
          pytest -v tests/

